// frontend/src/Layout/MainLayout/Header/index.jsx
// material ui

// other libraries

// project imports
import Notifications from '../../../components/Notifications';
import UserProfile from '../../../components/UserProfile/UserProfile';

const Header = () => {
  return (
    <>
      <div className="z-[999] bg-white fixed flex justify-end w-full shadow p-3 gap-5 align-middle h-14">
        <Notifications />
        <UserProfile />
      </div>
    </>
  );
};
export default Header;

// frontend-vue/src/layout/MainLayout/Header.vue
<script setup lang="ts">
import UserProfile from '@/components/home/UserProfile.vue'
import { Menu } from 'lucide-vue-next'

const emit = defineEmits<{
  hamburgerClick: [value: boolean]
}>()

</script>

<template>
  <div class="bg-white flex w-full shadow align-middle">
    <div class="flex justify-between w-full items-center p-3">
      <div class="cursor-pointer" @click="$emit('hamburgerClick', true)">
        <Menu class="h-6 w-6"></Menu>
      </div>
      <div class="flex gap-5">
        <UserProfile />
      </div>
    </div>
  </div>
</template>
