// frontend-react/src/components/UserProfile/UserProfile.jsx
import React from 'react';

import { useAuth } from '../Auth/AuthProvider';

import { Edit, LogOut } from 'lucide-react';
import { displayRole } from '../../utils';
import { Avatar, AvatarFallback, AvatarImage } from '../ui/avatar';
import { Button } from '../ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuTrigger,
} from '../ui/dropdown-menu';

export default function UserProfile() {
  const { user, logout } = useAuth();

  return (
    <>
      <div className="text-sm font-medium leading-none align-middle text-center self-center">
        {user?.userDto?.name ?? ''}
      </div>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <div className="flex">
            <Button
              variant="ghost"
              className="h-8 w-8 rounded-full self-center"
            >
              <Avatar className="h-9 w-9">
                <AvatarImage src="/avatar.png" alt="@shadcn" />
                <AvatarFallback>
                  {user?.userDto?.name
                    ?.toUpperCase()
                    .split(' ')
                    .map((x) => x[0])
                    .join('')}
                </AvatarFallback>
              </Avatar>
            </Button>
          </div>
        </DropdownMenuTrigger>
        <DropdownMenuContent className="w-56 z-[1000]" align="end" forceMount>
          <DropdownMenuLabel className="font-normal">
            <div className="flex flex-col space-y-1">
              <p className="text-sm font-medium leading-none">
                {displayRole(user?.userDto?.role ?? '')}
              </p>
              <p className="text-xs leading-none text-muted-foreground">
                {user?.userDto?.email ?? ''}
              </p>
            </div>
          </DropdownMenuLabel>
          <DropdownMenuSeparator />
          <DropdownMenuGroup>
            <DropdownMenuItem disabled>
              <Edit className="mr-2 h-4 w-4" />
              <span>Change Password</span>
              <DropdownMenuShortcut>🛠</DropdownMenuShortcut>
            </DropdownMenuItem>
          </DropdownMenuGroup>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={logout}>
            <LogOut className="mr-2 h-4 w-4" />
            <span>Log out</span>
            <DropdownMenuShortcut>🚪</DropdownMenuShortcut>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </>
  );
}

// frontend-vue/src/components/home/UserProfile.vue
<script setup lang="ts">
import { useAuthStore } from '@/stores/authStore'
import DropdownMenu from '../ui/dropdown-menu/DropdownMenu.vue'
import DropdownMenuTrigger from '../ui/dropdown-menu/DropdownMenuTrigger.vue'
import Button from '../ui/button/Button.vue'
import DropdownMenuContent from '../ui/dropdown-menu/DropdownMenuContent.vue'
import DropdownMenuLabel from '../ui/dropdown-menu/DropdownMenuLabel.vue'
import DropdownMenuSeparator from '../ui/dropdown-menu/DropdownMenuSeparator.vue'
import DropdownMenuItem from '../ui/dropdown-menu/DropdownMenuItem.vue'
import { LogOut } from 'lucide-vue-next'
import DropdownMenuShortcut from '../ui/dropdown-menu/DropdownMenuShortcut.vue'


const { auth, logout } = useAuthStore()
</script>

<template>
  <div class="text-sm font-medium leading-none align-middle text-center self-center">
    {{ auth?.userDto?.userName ?? '' }}
  </div>
  <DropdownMenu>
    <DropdownMenuTrigger asChild>
      <div className="flex">
        <Button variant="ghost" className="flex h-8 w-8 rounded-full self-center leading-none">
          <div class="flex self-center rounded-full border-primary/40 border-2 p-1">
            <img class="w-full h-full object-contain max-w-sm" src="@/assets/avatar.svg" />
            
          </div>
        </Button>
      </div>
    </DropdownMenuTrigger>
    <DropdownMenuContent class="w-56 z-[1000]" align="end">
      <DropdownMenuLabel class="font-normal">
        <div class="flex flex-col space-y-1">
          <p class="text-xs leading-none text-muted-foreground">
            {{ auth?.userDto?.userId ?? '' }}
          </p>
        </div>
      </DropdownMenuLabel>
      <DropdownMenuSeparator />
      <DropdownMenuItem @click="logout">
        <LogOut class="mr-2 h-4 w-4" />
        <span>Log out</span>
        <DropdownMenuShortcut>🚪</DropdownMenuShortcut>
      </DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>
